// Safe fallback data for when APIs are having issues
export const safeFallbackProducts = [
  {
    id: "temp-product-1",
    name: "Temporary Product 1",
    price: 50,
    description: "Temporary product while fixing data issues",
    quantity: 1,
    image: null,
    images: [],
    status: 'live',
    sale_state: 'LIVE',
    show_in_featured: true,
    show_in_coming_soon: false,
    show_in_new_releases: false,
    show_in_staff_picks: false,
    show_in_limited_editions: false,
    out_of_stock: false,
    weight: 0.3,
    length: 4,
    width: 3,
    height: 5,
    featured: true,
    staff_pick: false,
    limited_edition: false,
    drop_date: null,
    released_date: null,
    release_at: null
  },
  {
    id: "temp-product-2", 
    name: "Temporary Product 2",
    price: 75,
    description: "Another temporary product",
    quantity: 1,
    image: null,
    images: [],
    status: 'live',
    sale_state: 'LIVE',
    show_in_featured: true,
    show_in_coming_soon: false,
    show_in_new_releases: true,
    show_in_staff_picks: false,
    show_in_limited_editions: false,
    out_of_stock: false,
    weight: 0.3,
    length: 4,
    width: 3,
    height: 5,
    featured: true,
    staff_pick: false,
    limited_edition: false,
    drop_date: null,
    released_date: null,
    release_at: null
  }
]