#!/bin/bash

echo "🔧 Setting up Cloudinary environment variables in Vercel..."
echo ""
echo "You need to add these environment variables in your Vercel dashboard:"
echo ""
echo "1. Go to https://vercel.com/dashboard"
echo "2. Select your project: westcoastcollectibless"
echo "3. Go to Settings → Environment Variables"
echo "4. Add these variables for Production, Preview, and Development:"
echo ""
echo "CLOUDINARY_CLOUD_NAME = dxnp1razh"
echo "CLOUDINARY_API_KEY = 382984168596393"
echo "CLOUDINARY_API_SECRET = 755aTdmhTXv67e1Nksnn2e6MDII"
echo "CLOUDINARY_UPLOAD_PRESET_PRODUCT = westcoast_product_gallery"
echo ""
echo "5. Click 'Save' for each variable"
echo "6. Redeploy your project for changes to take effect"
echo ""
echo "OR use Vercel CLI (if you have it installed):"
echo ""
echo "vercel env add CLOUDINARY_CLOUD_NAME production"
echo "vercel env add CLOUDINARY_API_KEY production"
echo "vercel env add CLOUDINARY_API_SECRET production"
echo "vercel env add CLOUDINARY_UPLOAD_PRESET_PRODUCT production"