name: eBay CSV Import

on:
  workflow_dispatch:
  push:
    paths:
      - eBay-all-active-listings-report-2025-08-07-12257717404.csv

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i
      - run: node scripts/ebay_csv_to_products.mjs
        env:
          EBAY_CSV_PATH: eBay-all-active-listings-report-2025-08-07-12257717404.csv
      - run: node scripts/json_to_products_ts.mjs
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/ebay-import
          title: chore: refresh products from eBay CSV
          commit-message: chore: refresh products from eBay CSV
          body: Automated update of products from latest eBay CSV.
