name: Verify Cloudinary Images

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  verify-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install

    - name: Verify Cloudinary image configuration
      run: pnpm run verify:images
      env:
        # Note: In production, set these as repository secrets
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

    - name: Run TypeScript build check
      run: pnpm run build

    - name: Install Playwright
      run: pnpm exec playwright install --with-deps

    - name: Run image loading tests
      run: pnpm run test:images
      env:
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: image-test-results
        path: |
          test-results/
          playwright-report/
        retention-days: 7